# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170628_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='self_intro',
            name='photo',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='self_intro',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
