# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170702_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_number',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
